#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#Feh 
/usr/bin/feh --bg-fill $HOME/fondos/Samurai.jpg


# Polybar 
~/.config/polybar/./launch.sh &
/usr/local/bin/picom &

# Para quitar el borde de las ventanas
# bspc config border_with 0

# Para el burp pero no se que hace exactamente, preguntar al chat
wmname LG3D &
